export const USER_REPOSITORY = 'USER_REPOSITORY';
export const TEAM_REPOSITORY = 'TEAM_REPOSITORY';
export const SERVICE_GROUP_REPOSITORY = 'SERVICE_GROUP_REPOSITORY';
export const VERSION_REPOSITORY = 'VERSION_REPOSITORY';

export const DATA_SOURCE = 'DATA_SOURCE';
